#pragma once
#define SDL_MAIN_HANDLED

#define BOARD_WIDTH 8
#define BOARD_HEIGHT 8

#define SIZE_CELL_PIXEL 80
#define SIZE_EDGE 20

#define BOARD_X SIZE_EDGE
#define BOARD_Y SIZE_EDGE

#define WINDOW_HEIGHT 680
#define WINDOW_WIDTH 680
#define AMOUNT_OF_FILE_PICTURE 17

#define GAME_OVER_POPUP_WIDTH 480
#define GAME_OVER_POPUP_HEIGHT 322
#define GAME_OVER_POPUP_X ((WINDOW_WIDTH - GAME_OVER_POPUP_WIDTH) / 2)
#define GAME_OVER_POPUP_Y (((WINDOW_HEIGHT - GAME_OVER_POPUP_HEIGHT) / 2) + 1)

#define TEXT_GAME_OVER_WIDTH 320
#define TEXT_GAME_OVER_HEIGHT 70
#define TEXT_GAME_OVER_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_OVER_WIDTH) / 2)
#define TEXT_GAME_OVER_Y (GAME_OVER_POPUP_Y + 5)
#define TEXT_GAME_OVER_SIZE 24

#define TEXT_GAME_RESULT_WIDTH 320
#define TEXT_GAME_RESULT_HEIGHT 70
#define TEXT_GAME_RESULT_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_GAME_RESULT_WIDTH) / 2)
#define TEXT_GAME_RESULT_Y (GAME_OVER_POPUP_Y + SIZE_CELL_PIXEL + 5)
#define TEXT_GAME_RESULT_SIZE 24

#define TEXT_PLAY_AGAIN_WIDTH 160
#define TEXT_PLAY_AGAIN_HEIGHT 70
#define TEXT_PLAY_AGAIN_X (GAME_OVER_POPUP_X + (GAME_OVER_POPUP_WIDTH - TEXT_PLAY_AGAIN_WIDTH) / 2)
#define TEXT_PLAY_AGAIN_Y (GAME_OVER_POPUP_Y + SIZE_CELL_PIXEL * 2 + 5)
#define TEXT_PLAY_AGAIN_SIZE 24

#define YES_CELL_WIDTH (SIZE_CELL_PIXEL - 10)
#define YES_CELL_HEIGHT (SIZE_CELL_PIXEL - 10)
#define YES_CELL_X (GAME_OVER_POPUP_X + SIZE_CELL_PIXEL + 5)
#define YES_CELL_Y (GAME_OVER_POPUP_Y + SIZE_CELL_PIXEL * 3 + 5)

#define NO_CELL_WIDTH (SIZE_CELL_PIXEL - 10)
#define NO_CELL_HEIGHT (SIZE_CELL_PIXEL - 10)
#define NO_CELL_X (YES_CELL_X + SIZE_CELL_PIXEL * 3)
#define NO_CELL_Y YES_CELL_Y

enum CellType {
	KING, //Vua
	QUEEN, //Hau
	BISHOP, //Tuong
	CASTLE, //Xe
	KNIGHT, //Ma
	PAWN,	//Tot
	NONE
};

enum Color {
	WHITE = 1,
	BLACK = -1
};

struct Coordinate {
	int x;
	int y;
};
